[package]
name = "otpmdec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.3.3"
protobuf = "3.2.0"
urlencoding = "2.1.2"

[build-dependencies]
protobuf-codegen = "3.2.0"
